version: '3'

services:
  runner-build:
    build:
      context: .
      dockerfile: runner.Dockerfile
    tty: true
    command: ${GITHUB_USER} "test_repo" ${GITHUB_TOKEN} "myrunner"
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}

  orc:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    tty: true
    volumes:
        - .:/work
        - /var/run/docker.sock:/var/run/docker.sock
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}

  runner:
    image: zzzcat/github-runner
    tty: true
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}