version: '3'

services:
  orchestrator:
    image: zzzcat/github-runner-orchestrator:latest
    tty: true
    volumes:
        - .:/work
        - /var/run/docker.sock:/var/run/docker.sock
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}

  runner:
    image: zzzcat/github-runner:latest
    tty: true
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}