version: '3'

services:
  autobuild-docker:
    image: zzzcat/dispshell:docker
    tty: true
    working_dir: /work
    command: bash push-dockerhub.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/work/.:ro
    environment:
      DOCKERHUB_USER: ${DOCKERHUB_USER}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    tty: true
    entrypoint: bash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${WORKER_DIR}/work-runner/_work:/work-runner/_work:rw
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
