version: '3'

services:
  autobuild-docker:
    image: zzzcat/dispshell:docker
    tty: true
    working_dir: /work
    command: bash push-dockerhub.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/work/.:ro
    environment:
      DOCKERHUB_USER: ${DOCKERHUB_USER}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}

  runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    tty: true
    entrypoint: bash
    #command: bash
    #command: ${GITHUB_USER} "test_repo" ${GITHUB_TOKEN} "myrunner"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
