version: '3'

services:
  runner:
    image: zzzcat/github-runner:latest
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /host-share:/host-share
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}