version: '3'

services:
  runner:
    image: zzzcat/github-runner:latest
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
      CIFS_USER: ${CIFS_USER}
      CIFS_PASS: ${CIFS_PASS}
      CIFS_HOST: ${CIFS_HOST}
      CIFS_REMOTE_PATH: ${CIFS_REMOTE_PATH}
      CIFS_LOCAL_PATH: ${CIFS_LOCAL_PATH}
    privileged: true
    cap_add:
      - SYS_ADMIN
