version: '3'

services:
  runner:
    image: zzzcat/github-runner:latest
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ${WORKER_DIR}/work-runner/_work:/work-runner/_work:rw
      #- /C/Users/g/OneDrive/devel/gggcat@github/github-runner/orchestrator/work-runner/_work:/work-runner/_work:rw
    # 環境変数
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
