# This is a basic workflow to help you get started with Actions
name: Build Runner Ochestrator

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
      - 'orchestrator/**'
      - '!orchestrator/reference_scripts**'
  #schedule:
    # At 00:00 on Monday.
    #- cron: '0 0 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: auto build docker image
        shell: bash
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          cd orchestrator
          docker-compose run autobuild-docker
          docker-compose down
